### ISSUE TITLE
Getting lost

### ISSUE THREAD

**Issue by towsey** [QutEcoacoustics/baw-client#296]
I logged on.
I went to Samford ERF Project.
I clicked on the Frog Pond site. Once I am in the Frog Pond Site there appears to be no indication as to which project I am in.  Could not the heading indicate Project/Site?

And when I click on Visualise, for this project and site, very little makes sense. I cannot work out how the two time scales (variable and fixed) relate to one another.
~~Cheers, Michael~~

**Comment by atruskie** [comment]
The first part of your issue has been moved here: https://github.com/QutBioacoustics/baw-server/issues/322

As for the second part, the blue shaded area demonstrates the link between the variable resolution and the fixed resolution.

See https://gyazo.com/0cc4e36ee0fb58409f78fcccb363cb3e

What can we do to make that association clearer?

**Comment by towsey** [comment]
Concerning the image you sent, does green mean the same in the top and bottom panels? In the top panel stripes suggest very little recording available. Bottom panel suggests continuous recording available. Also I found the "Go to" links did not work after playing a while. We can talk to morrow.

**Comment by atruskie** [comment]
The top panel shows the correct amount of audio.

The bottom panel is showing the incorrect amount of audio. This is because the tiles in the bottom panel are not showing audio - they should be showing false colour content but the images are not available. 
We left it like this as a known limitation assuming it would be largely masked by the false colour tiles being available.

We could do a fix to ensure the coloured sections in the bottom section always represent audio. Would that solve the UI problem for you?

For the broken links: collect URLs and screenshots when you find them and place into a separate issue.

**Comment by atruskie** [comment]
The display of incorrectly sized blocks of audio has been fixed in 7fbf0a1a33f740067c370837dbf42e7141041a9a
